mars_lighthouse.settings:
  type: config_object
  label: 'Lighthouse API settings'
  mapping:
    client_id:
      type: string
      label: 'Client ID'
    client_secret:
      type: string
      label: 'Client Secret'
    api_key:
      type: string
      label: 'API key'
    base_path:
      type: string
      label: 'Base path'
    port:
      type: integer
      label: 'Port'
    sync_mode:
      type: boolean
      label: 'Use bulk sync mode'
    api_version:
      type: string
      label: 'API version'

mars_lighthouse.mapping:
  type: config_object
  label: 'Lighthouse mapping configuration'
  mapping:
    media:
      type: mapping
      mapping:
        field_external_id:
          type: string
          label: 'assetId'
        field_segment:
          type: string
          label: 'segment'
        field_brand:
          type: string
          label: 'brand'
        field_sub_brand:
          type: string
          label: 'subBrand'
        field_category:
          type: string
          label: 'category'
        field_sub_type:
          type: string
          label: 'subType'
        field_region:
          type: string
          label: 'region'
        field_marketing_country:
          type: string
          label: 'mktingCountry'
        field_language:
          type: string
          label: 'language'
        field_agency:
          type: string
          label: 'agencyPartnerVendor'
        field_last_mod_date:
          type: string
          label: 'lastModDate'
        name:
          type: string
          label: 'assetName'
        field_version_id:
          type: string
          label: 'versionIdOTMM'
        field_original_external_id:
          type: string
          label: 'origAssetId'
    file:
      type: mapping
      mapping:
        filename:
          type: string
          label: 'assetName'
        uri:
          type: string
          label: 'urls.001orig'
        filemime:
          type: string
          label: 'fileType'
